services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careers_backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - careers_network
    env_file: ".env"
    restart: on-failure
    environment:
      DEBUG: "${DEBUG}"

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/database
    networks:
      - careers_network

networks:
  careers_network:

volumes:
  postgres_data:
